[package]
name = "three"
version = "0.1.0"
edition = "2021"
default-run = "three"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "three"
path = "main.rs"

[[bin]]
name = "three2"
path = "old.rs"
